[project]
name = "uv-demo-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepface>=0.0.99",
    "fastapi>=0.135.0",
    "numpy>=2.4.2",
    "opencv-python>=4.13.0.92",
    "pygame",
    "python-multipart>=0.0.22",
    "tf-keras>=2.20.1",
    "uvicorn>=0.41.0",
]
