namespace Relevantz.PhotoValidator.Common.Constants
{
    public static class ExcelHeaders
    {
        public const string Email = "Email";
        public const string FirstName = "FirstName";
        public const string LastName = "LastName";
        public const string EmploymentType = "EmploymentType";
        public const string EmploymentStatus = "EmploymentStatus";
        public const string JoiningDate = "JoiningDate";
        public const string EmployeeType = "EmployeeType";
        public const string Role = "Role";
        public const string Department = "Department";
        public const string MobileNumber = "MobileNumber";
        public const string Gender = "Gender";
    }
    public static class ExcelMessages
    {
        public const string BulkImportInstructions = "Bulk User Import Instructions";
        public const string EmployeeIdAutoGenerated = "IMPORTANT: Employee IDs are AUTO-GENERATED";
        public const string DoNotIncludeEmployeeId = "Do NOT include Employee ID column. IDs will be assigned automatically.";
        public const string NoWorksheetsError = "Excel file contains no worksheets";
        public const string EmptyWorksheetError = "Excel worksheet is empty";
        public const string NoDataRowsError = "Excel file must contain at least one data row besides the header";
        public const string NoValidUsersError = "No valid users found in Excel file";
    }
    public static class EmploymentTypeValues
    {
        public const string Permanent = "Permanent";
        public const string Contract = "Contract";
        public const string Temporary = "Temporary";
        public const string Intern = "Intern";
        public const string Probation = "Probation";
        public static string[] GetAll() => new[] { Permanent, Contract, Temporary, Intern, Probation };
        public static string GetCommaSeparated() => string.Join(",", GetAll().Select(x => $"\"{x}\""));
    }
    public static class EmploymentStatusValues
    {
        public const string Active = "Active";
        public const string Inactive = "Inactive";
        public const string OnLeave = "OnLeave";
        public static string[] GetAll() => new[] { Active, Inactive, OnLeave };
        public static string GetCommaSeparated() => string.Join(",", GetAll().Select(x => $"\"{x}\""));
    }
    public static class EmployeeTypeValues
    {
        public const string FullTime = "FullTime";
        public const string PartTime = "PartTime";
        public const string Intern = "Intern";
        public static string[] GetAll() => new[] { FullTime, PartTime, Intern };
        public static string GetCommaSeparated() => string.Join(",", GetAll().Select(x => $"\"{x}\""));
    }
    public static class GenderValues
    {
        public const string Male = "Male";
        public const string Female = "Female";
        public const string PreferNotToSay = "PreferNotToSay";
        public static string[] GetAll() => new[] { Male, Female, PreferNotToSay };
        public static string GetCommaSeparated() => string.Join(",", GetAll().Select(x => $"\"{x}\""));
    }
}
